- project:
    check:
      jobs:
        - noop
        - matt-check
        - jhewitt-sandbox
    gate:
      jobs:
        - noop
        - matt-check
        - jhewitt-sandbox
    post:
      jobs:
        - sandbox-post
